namespace Skidjakt.Core.DTOs;

public record DealDto(
    int Id,
    string Agency,
    string ExternalId,
    string SourceUrl,
    string Destination,
    string Country,
    DateOnly? DepartureDate,
    DateOnly? ReturnDate,
    int? WeekNumber,
    int DurationNights,
    string? TransportType,
    string? DepartureCity,
    string? AccommodationName,
    string? AccommodationType,
    int? StarRating,
    int PricePerPerson,
    int? OriginalPrice,
    int? DiscountAmount,
    bool IncludesFlight,
    bool IncludesLiftPass,
    bool IncludesMeals,
    bool IncludesTransfer,
    string? MealDescription,
    int? LiftPassDays,
    DateTime FirstSeen,
    DateTime LastSeen,
    bool IsActive
);
